version: '2'
services:
  spring-boot-compose:
    image: rest-service-complete:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgpool-compose:5432/db_test
    depends_on:
      - pgpool-compose
  postgres-compose-master-1:
    image: bitnami/postgresql-repmgr:14.4.0-debian-11-r9
    ports:
      - 5432
    volumes:
      - postgres_master_data:/bitnami/postgresql
    environment:
      - REPMGR_PARTNER_NODES=postgres-compose-master-1,postgres-compose-replica-1,postgres-compose-replica-2
      - REPMGR_NODE_NAME=postgres-compose-master-1
      - REPMGR_NODE_NETWORK_NAME=postgres-compose-master-1
      - REPMGR_NODE_ID=1
      - REPMGR_PRIMARY_HOST=postgres-compose-master-1
      - REPMGR_PASSWORD=repmgrpass
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE=db_test
  postgres-compose-replica-1:
    image: bitnami/postgresql-repmgr:14.4.0-debian-11-r9
    ports:
      - 5432
    volumes:
      - postgres_replica_1_data:/bitnami/postgresql
    environment:
      - REPMGR_PARTNER_NODES=postgres-compose-master-1,postgres-compose-replica-1,postgres-compose-replica-2
      - REPMGR_NODE_NAME=postgres-compose-replica-1
      - REPMGR_NODE_NETWORK_NAME=postgres-compose-replica-1
      - REPMGR_NODE_ID=2
      - REPMGR_PRIMARY_HOST=postgres-compose-master-1
      - REPMGR_PASSWORD=repmgrpass
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE=db_test
  postgres-compose-replica-2:
    image: bitnami/postgresql-repmgr:14.4.0-debian-11-r9
    ports:
      - 5432
    volumes:
      - postgres_replica_2_data:/bitnami/postgresql
    environment:
      - REPMGR_PARTNER_NODES=postgres-compose-master-1,postgres-compose-replica-1,postgres-compose-replica-2
      - REPMGR_NODE_NAME=postgres-compose-replica-2
      - REPMGR_NODE_NETWORK_NAME=postgres-compose-replica-2
      - REPMGR_NODE_ID=3
      - REPMGR_PRIMARY_HOST=postgres-compose-master-1
      - REPMGR_PASSWORD=repmgrpass
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE=db_test
  pgpool-compose:
    image: bitnami/pgpool:4.3.2-debian-11-r16
    ports:
      - 5432
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres-compose-master-1:5432,1:postgres-compose-replica-1:5432,2:postgres-compose-replica-2:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=mysecretpassword
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=mysecretpassword
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=mysecretpassword
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
    depends_on:
      - postgres-compose-master-1
volumes:
  postgres_master_data:
    driver: local
  postgres_replica_1_data:
    driver: local
  postgres_replica_2_data:
    driver: local